apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-everything

resources:
  - ../../base

images:
  - name: ghcr.io/4eyedengineer/mcp-everything/backend
    newName: harbor.192.168.1.124.nip.io/library/mcp-backend
    newTag: latest
  - name: ghcr.io/4eyedengineer/mcp-everything/frontend
    newName: harbor.192.168.1.124.nip.io/library/mcp-frontend
    newTag: latest

patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
